Repository nprint/nprintml, pull requests merged in 2020-11, with the labels that each got.

#9 Automl
  src/nprintml/automl.py
  test/binary_test.csv.gz
  test/multiclass_test.csv.gz
Labels: enhancement

#10 command alias for `nprintml`: `nml`
  README.md
  setup.py
Labels: documentation, enhancement

#11 Label aggregation
  src/nprintml/label_aggregation.py
Labels: enhancement

#12 nprintML pipeline with nPrint integration
  README.md
  setup.py
  src/nprintml/cli.py
  src/nprintml/net/execute.py
  src/nprintml/net/install.py
  src/nprintml/net/step.py
  src/nprintml/pipeline.py
Labels: enhancement

#13 label-aggregation step of pipeline
  setup.py
  src/nprintml/cli.py
  src/nprintml/label/__init__.py
  src/nprintml/label/aggregator/__init__.py
  src/nprintml/label/aggregator/base.py
  src/nprintml/label/aggregator/index.py
  src/nprintml/label/aggregator/pcap.py
  src/nprintml/label/step.py
  src/nprintml/label_aggregation.py
  src/nprintml/net/step.py
  src/nprintml/pipeline.py
Labels: enhancement

#14 integration of AutoML into CLI pipeline
  setup.py
  src/nprintml/automl.py
  src/nprintml/cli.py
  src/nprintml/learn/__init__.py
  src/nprintml/learn/automl.py
  src/nprintml/learn/step.py
  src/nprintml/net/step.py
Labels: enhancement

#15 update PCAP label aggregator to copy over labels and work correctly
  src/nprintml/label/aggregator/pcap.py
Labels: bug
